name: delete-ghcr-images

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  delete-images:
    name: Delete image from ghcr.io
    runs-on: ubuntu-latest
    steps:
      - name: Delete image
        uses: bots-house/ghcr-delete-image-action@v1.0.0
        with:
          owner: codepraxis-io
          name: spring-music
          token: ${{ secrets.GHCR_TOKEN }}
          tag: 2.0.0-temurin-17-jre-jammy
