name: delete-ghcr-images

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  delete-images:
    name: Delete image from ghcr.io
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: ['2.0.0-amazoncorretto-17-alpine3-15',
              '2.0.0-distroless-java17-debian11',
              '2.0.0-distroless-java17-debian11-multistage',
              '2.0.0-distroless-java11-debian11-multistage']
    steps:
      - name: Delete image
        uses: bots-house/ghcr-delete-image-action@v1.0.0
        with:
          owner: codepraxis-io
          name: spring-music
          token: ${{ secrets.GHCR_TOKEN }}
          tag: ${{ matrix.tag }}
