name: mirror-gcr-images

on:
  schedule:
    - cron: '0 6 * * *'
  push:
    branches:
      - main
    paths:
      - .github/workflows/mirror-gcr-images.yml
  workflow_dispatch:
jobs:
  pipeline:
    uses: codepraxis-io/github-actions/.github/workflows/docker-image-mirror-workflow.yml@main
    with:
      upstream-registry: gcr.io
      upstream-image-list: '["distroless/java11-debian11:latest", "distroless/java17-debian11:latest"]'
    secrets:
      DESTINATION_REGISTRY_USERNAME: ${{ secrets.GH_PACKAGES_USERNAME }} 
      DESTINATION_REGISTRY_PASSWORD: ${{ secrets.GH_PAT }}
